# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Install project and dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
