"""
Axion HDL XDC Constraint Generator Module

This module generates Xilinx Design Constraints (XDC) files for the
generated AXI4-Lite register interface modules (*_axion_reg).

For every analyzed module a `<module>_axion_reg.xdc` file is produced that
declares timing exceptions (false paths) for the module-side register
signals:

- RO registers are inputs of the register module (module logic -> AXI):
  constrained with `set_false_path -to`.
- RW/WO registers are outputs of the register module (AXI -> module logic):
  constrained with `set_false_path -from`.

The constraints are instance-independent: instead of hard-coding an
instance path (which is chosen by the user, not by Axion-HDL), the cells
are located through their module reference name:

    get_cells -hierarchical -filter {REF_NAME == <module>_axion_reg ||
                                     ORIG_REF_NAME == <module>_axion_reg}

This matches every instance of the module anywhere in the design
hierarchy, regardless of the instance names chosen by the integrator.
Vivado keeps ORIG_REF_NAME intact even when synthesis renames or uniquifies
the module, so the constraints survive hierarchy rebuilding.

Strobe outputs (*_rd_strobe / *_wr_strobe) are single-cycle pulses and are
intentionally NOT false-pathed; the corresponding constraints are emitted
commented-out with an explanatory note.
"""

import os


class XDCGenerator:
    """Generates Xilinx XDC timing constraint files for register modules."""

    def __init__(self, output_dir):
        """
        Initialize XDC generator.

        Args:
            output_dir: Directory where generated .xdc files are written
        """
        self.output_dir = output_dir

    def generate_xdc(self, module_data):
        """
        Generate the XDC constraint file for a single module.

        Args:
            module_data: Parsed module dictionary (same structure consumed
                         by VHDLGenerator/SystemVerilogGenerator)

        Returns:
            Path of the generated .xdc file
        """
        module_name = module_data['name']
        entity_name = f"{module_name}_axion_reg"

        lines = self._generate_header(module_data, entity_name)
        lines.extend(self._generate_cell_lookup(entity_name))
        lines.extend(self._generate_register_constraints(module_data))
        lines.extend(self._generate_packed_register_constraints(module_data))
        lines.extend(self._generate_strobe_notes(module_data))

        output_path = os.path.join(self.output_dir, f"{entity_name}.xdc")
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines) + '\n')

        return output_path

    # ------------------------------------------------------------------
    # Section generators
    # ------------------------------------------------------------------

    def _generate_header(self, module_data, entity_name):
        """Generate the file header with usage notes."""
        from axion_hdl import __version__

        lines = [
            "#" * 78,
            f"# {entity_name}.xdc",
            f"# Timing constraints for the {entity_name} AXI4-Lite register interface",
            "#",
            f"# Generated by Axion-HDL v{__version__}",
            "#",
            "# This file is INSTANCE-INDEPENDENT: cells are located via their module",
            "# reference name (REF_NAME / ORIG_REF_NAME), so the constraints apply to",
            "# every instance of the module anywhere in the design hierarchy, no",
            "# matter which instance names the integrator chose.",
            "#",
            "# Usage:",
            "#   Add this file to the Vivado project as a normal constraint file",
            "#   (add_files / read_xdc). It must be processed together with (or",
            "#   after) the constraints that create the design clocks.",
            "#",
            "# Notes:",
            "#   * If the module is not (yet) instantiated in the design, Vivado",
            "#     reports 'no valid object(s) found' critical warnings for these",
            "#     constraints. They are harmless and disappear once the module is",
            "#     instantiated.",
            "#   * The false paths below declare the module-side register signals",
            "#     as asynchronous / quasi-static. The consuming logic must treat",
            "#     them accordingly (e.g. slow-changing configuration values or",
            "#     status values that tolerate sampling skew between bits).",
        ]

        if not module_data.get('cdc_enabled'):
            lines.extend([
                "#",
                "#   * WARNING: CDC is DISABLED for this module. The register",
                "#     interface and the module-side signals share the axi_aclk",
                "#     domain. Only apply these false paths if the logic connected",
                "#     to the register signals runs in a different (asynchronous)",
                "#     clock domain; otherwise remove this file to keep the paths",
                "#     timed.",
            ])

        lines.append("#" * 78)
        lines.append("")
        return lines

    def _generate_cell_lookup(self, entity_name):
        """Generate the instance-independent cell lookup."""
        return [
            "# Locate every instance of the register module (instance-name agnostic).",
            "# ORIG_REF_NAME keeps matching when synthesis renames/uniquifies the module.",
            f"set axion_cells [get_cells -hierarchical -filter {{REF_NAME == {entity_name} || ORIG_REF_NAME == {entity_name}}}]",
            "",
        ]

    def _generate_register_constraints(self, module_data):
        """Generate false-path constraints for standalone (non-packed) registers."""
        lines = []
        for reg in module_data.get('registers', []):
            if reg.get('is_packed'):
                continue
            lines.extend(self._false_path_for_signal(
                reg['signal_name'], reg['access_mode'],
                reg.get('description', '')))
        return lines

    def _generate_packed_register_constraints(self, module_data):
        """Generate false-path constraints for packed register fields."""
        lines = []
        for packed_reg in module_data.get('packed_registers', []):
            for field in packed_reg.get('fields', []):
                sig_name = f"{packed_reg['reg_name']}_{field['name']}"
                lines.extend(self._false_path_for_signal(
                    sig_name, field['access_mode'],
                    field.get('description', '')))
        return lines

    def _generate_strobe_notes(self, module_data):
        """Emit commented-out constraints for strobe outputs."""
        strobe_signals = []

        for reg in module_data.get('registers', []):
            if reg.get('is_packed'):
                continue
            if reg.get('read_strobe'):
                strobe_signals.append(f"{reg['signal_name']}_rd_strobe")
            if reg.get('write_strobe'):
                strobe_signals.append(f"{reg['signal_name']}_wr_strobe")

        for packed_reg in module_data.get('packed_registers', []):
            if packed_reg.get('read_strobe'):
                strobe_signals.append(f"{packed_reg['reg_name']}_rd_strobe")
            if packed_reg.get('write_strobe'):
                strobe_signals.append(f"{packed_reg['reg_name']}_wr_strobe")

        if not strobe_signals:
            return []

        lines = [
            "# Strobe outputs are single-cycle pulses in the axi_aclk domain and are",
            "# intentionally NOT false-pathed: a false path would hide real timing",
            "# failures on pulse consumers. Uncomment only if the receiving logic",
            "# treats the strobe asynchronously (e.g. via a pulse synchronizer).",
        ]
        for sig in strobe_signals:
            lines.append(
                f"# set_false_path -from [get_pins -of_objects $axion_cells "
                f"-filter {{NAME =~ */{sig}}}]")
        lines.append("")
        return lines

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _false_path_for_signal(self, signal_name, access_mode, description=""):
        """
        Build the false-path constraint lines for a single register signal.

        RO registers are module inputs -> constrain paths INTO the module
        (-to). RW/WO registers are module outputs -> constrain paths OUT of
        the module (-from). Both the scalar pin name and the vector bit pins
        (name[*]) are matched.
        """
        if access_mode == 'RO':
            direction_arg = '-to'
            comment_dir = 'module -> AXI (input)'
        else:  # RW or WO
            direction_arg = '-from'
            comment_dir = 'AXI -> module (output)'

        desc = f" - {description}" if description else ""
        pin_filter = (f"{{NAME =~ */{signal_name} || "
                      f"NAME =~ */{signal_name}[*]}}")
        return [
            f"# {signal_name} ({access_mode}, {comment_dir}){desc}",
            f"set_false_path {direction_arg} [get_pins -of_objects $axion_cells "
            f"-filter {pin_filter}]",
            "",
        ]
