/**
 * @file i2c_master_regs.h
 * @brief Register definitions for i2c_master module
 * @note Generated by Axion HDL - Do not edit manually
 *
 * All register definitions use module prefix to avoid namespace collisions
 * when multiple modules are included in the same project.
 */

#ifndef I2C_MASTER_REGS_H
#define I2C_MASTER_REGS_H

#include <stdint.h>

/* Module Base Address */
#define I2C_MASTER_BASE_ADDR    0x40002000

/* Register Address Offsets (relative to base) */
#define I2C_MASTER_CTRL_OFFSET    0x00  /* Packed register: CTRL */
#define I2C_MASTER_STATUS_OFFSET    0x04  /* Packed register: STATUS */
#define I2C_MASTER_PRESCALE_OFFSET    0x08  /* Packed register: PRESCALE */
#define I2C_MASTER_DATA_OFFSET    0x0C  /* Packed register: DATA */

/* Absolute Register Addresses */
#define I2C_MASTER_CTRL_ADDR    0x00
#define I2C_MASTER_STATUS_ADDR    0x04
#define I2C_MASTER_PRESCALE_ADDR    0x08
#define I2C_MASTER_DATA_ADDR    0x0C

/* Signal Width Definitions (for multi-register signals) */
/* No signals wider than 32 bits */

/* Register Access Macros (using module base address) */
/* Helper macros for bit field access */
#ifndef GET_FIELD
#define GET_FIELD(val, mask, shift)    (((val) & (mask)) >> (shift))
#endif

#ifndef SET_FIELD
#define SET_FIELD(val, mask, shift, new_val)    (((val) & ~(mask)) | (((new_val) << (shift)) & (mask)))
#endif
#define I2C_MASTER_READ_CTRL()    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_CTRL_OFFSET)))
#define I2C_MASTER_READ_STATUS()    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_STATUS_OFFSET)))
#define I2C_MASTER_READ_PRESCALE()    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_PRESCALE_OFFSET)))
#define I2C_MASTER_READ_DATA()    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_DATA_OFFSET)))

#define I2C_MASTER_WRITE_CTRL(val)    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_CTRL_OFFSET)) = (val))
#define I2C_MASTER_WRITE_PRESCALE(val)    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_PRESCALE_OFFSET)) = (val))
#define I2C_MASTER_WRITE_DATA(val)    (*((volatile uint32_t*)(I2C_MASTER_BASE_ADDR + I2C_MASTER_DATA_OFFSET)) = (val))

/* Bit Field Masks and Shifts (for packed registers) */
#define I2C_MASTER_CTRL_ENABLE_MASK    0x1
#define I2C_MASTER_CTRL_ENABLE_SHIFT   0
#define I2C_MASTER_CTRL_START_MASK    0x2
#define I2C_MASTER_CTRL_START_SHIFT   1
#define I2C_MASTER_CTRL_STOP_MASK    0x4
#define I2C_MASTER_CTRL_STOP_SHIFT   2
#define I2C_MASTER_STATUS_BUSY_MASK    0x1
#define I2C_MASTER_STATUS_BUSY_SHIFT   0
#define I2C_MASTER_STATUS_ACK_MASK    0x2
#define I2C_MASTER_STATUS_ACK_SHIFT   1
#define I2C_MASTER_STATUS_ARBLOST_MASK    0x4
#define I2C_MASTER_STATUS_ARBLOST_SHIFT   2
#define I2C_MASTER_PRESCALE_VALUE_MASK    0x1
#define I2C_MASTER_PRESCALE_VALUE_SHIFT   0
#define I2C_MASTER_DATA_BYTE_MASK    0x1
#define I2C_MASTER_DATA_BYTE_SHIFT   0

/* Register Default Values */
#define I2C_MASTER_CTRL_DEFAULT    0x00000000
#define I2C_MASTER_STATUS_DEFAULT    0x00000000
#define I2C_MASTER_PRESCALE_DEFAULT    0x00000000
#define I2C_MASTER_DATA_DEFAULT    0x00000000

/* Register Structure */
typedef struct {
    volatile uint32_t CTRL;  /* 0x00 - RW - Packed register: CTRL */
    volatile uint32_t STATUS;  /* 0x04 - RO - Packed register: STATUS */
    volatile uint32_t PRESCALE;  /* 0x08 - RW - Packed register: PRESCALE */
    volatile uint32_t DATA;  /* 0x0C - RW - Packed register: DATA */
} i2c_master_regs_t;

/* Access register block as structure */
#define I2C_MASTER_REGS    ((volatile i2c_master_regs_t*)(I2C_MASTER_BASE_ADDR))

#endif /* I2C_MASTER_REGS_H */
