--------------------------------------------------------------------------------
-- File: spi_master_1_axion_reg.vhd
-- Description: AXI Register Interface Module
-- Generated by Axion HDL
--
-- Module: spi_master_1
-- Source: spi_master.yaml
-- Author: bugratufan
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity spi_master_1_axion_reg is
    generic (
        BASE_ADDR : std_logic_vector(31 downto 0) := x"40001000"
    );
    port (
        -- AXI4-Lite Interface
        axi_aclk    : in  std_logic;
        axi_aresetn : in  std_logic;
        
        -- AXI Write Address Channel
        axi_awaddr  : in  std_logic_vector(31 downto 0);
        axi_awvalid : in  std_logic;
        axi_awready : out std_logic;
        
        -- AXI Write Data Channel
        axi_wdata   : in  std_logic_vector(31 downto 0);
        axi_wstrb   : in  std_logic_vector(3 downto 0);
        axi_wvalid  : in  std_logic;
        axi_wready  : out std_logic;
        
        -- AXI Write Response Channel
        axi_bresp   : out std_logic_vector(1 downto 0);
        axi_bvalid  : out std_logic;
        axi_bready  : in  std_logic;
        
        -- AXI Read Address Channel
        axi_araddr  : in  std_logic_vector(31 downto 0);
        axi_arvalid : in  std_logic;
        axi_arready : out std_logic;
        
        -- AXI Read Data Channel
        axi_rdata   : out std_logic_vector(31 downto 0);
        axi_rresp   : out std_logic_vector(1 downto 0);
        axi_rvalid  : out std_logic;
        axi_rready  : in  std_logic;
        
        -- Register Signals
        
        -- Packed Register Fields (Subregisters)
        -- Also includes aggregated strobe signals for parent registers
        CTRL_ENABLE : out std_logic;  -- Enable the SPI master
        CTRL_CPOL : out std_logic;  -- Clock polarity
        CTRL_CPHA : out std_logic;  -- Clock phase
        CTRL_LOOPBACK : out std_logic;  -- Loopback mode enable
        STATUS_BUSY : in  std_logic;  -- Transfer in progress
        STATUS_TX_EMPTY : in  std_logic;  -- TX FIFO empty
        STATUS_RX_VALID : in  std_logic;  -- RX data valid
        DIV_DIVISOR : out std_logic;  -- Clock divisor value (f_sclk = f_clk / (2 * (DIVISOR + 1)))
        TX_DATA_DATA : out std_logic;  -- Data byte to transmit
        RX_DATA_DATA : in  std_logic  -- Last received data byte
    );
end entity spi_master_1_axion_reg;

architecture rtl of spi_master_1_axion_reg is
    
    -- AXI4-Lite Compliant State Machine
    -- Supports independent address and data channels per AXI-LITE-005
    type axi_state_type is (IDLE, WR_WAIT_ADDR, WR_WAIT_DATA, WR_DO_WRITE, WR_RESP, RD_ADDR, RD_DATA);
    signal axi_state : axi_state_type;
    
    -- Internal signals for write transaction
    signal wr_addr_reg : std_logic_vector(31 downto 0);
    signal wr_data_reg : std_logic_vector(31 downto 0);
    signal wr_strb_reg : std_logic_vector(3 downto 0);
    
    -- Internal signals for read transaction
    signal rd_addr_reg : std_logic_vector(31 downto 0);
    signal rd_data_reg : std_logic_vector(31 downto 0);
    
    -- Access control
    signal wr_access_error : std_logic;
    signal rd_access_error : std_logic;
    signal wr_addr_valid_n : std_logic;  -- Combinational write address invalid flag
    signal rd_addr_valid_n : std_logic;  -- Combinational read address invalid flag
    
    -- Write trigger signal
    signal do_reg_write : std_logic;
    
    -- Register storage
    
    -- Internal signals for packed registers (storage for RW/WO, combined for RO)
    signal CTRL_reg : std_logic_vector(31 downto 0) := (others => '0'); -- AXI storage (RW/WO bits)
    signal CTRL_val : std_logic_vector(31 downto 0) := (others => '0'); -- Combined read value
    signal STATUS_reg : std_logic_vector(31 downto 0) := (others => '0'); -- AXI storage (RW/WO bits)
    signal STATUS_val : std_logic_vector(31 downto 0) := (others => '0'); -- Combined read value
    signal DIV_reg : std_logic_vector(31 downto 0) := (others => '0'); -- AXI storage (RW/WO bits)
    signal DIV_val : std_logic_vector(31 downto 0) := (others => '0'); -- Combined read value
    signal TX_DATA_reg : std_logic_vector(31 downto 0) := (others => '0'); -- AXI storage (RW/WO bits)
    signal TX_DATA_val : std_logic_vector(31 downto 0) := (others => '0'); -- Combined read value
    signal RX_DATA_reg : std_logic_vector(31 downto 0) := (others => '0'); -- AXI storage (RW/WO bits)
    signal RX_DATA_val : std_logic_vector(31 downto 0) := (others => '0'); -- Combined read value
    
    
begin
    
    ---------------------------------------------------------------------------
    -- Packed Register Mapping (Subregister connections)
    ---------------------------------------------------------------------------
    -- Connections for CTRL
    process(CTRL_reg)
    begin
        CTRL_val <= (others => '0');
        CTRL_val(0) <= CTRL_reg(0);
        CTRL_ENABLE <= CTRL_reg(0);
        CTRL_val(1) <= CTRL_reg(1);
        CTRL_CPOL <= CTRL_reg(1);
        CTRL_val(2) <= CTRL_reg(2);
        CTRL_CPHA <= CTRL_reg(2);
        CTRL_val(3) <= CTRL_reg(3);
        CTRL_LOOPBACK <= CTRL_reg(3);
    end process;
    
    -- Connections for STATUS
    process(STATUS_reg, STATUS_BUSY, STATUS_TX_EMPTY, STATUS_RX_VALID)
    begin
        STATUS_val <= (others => '0');
        STATUS_val(0) <= STATUS_BUSY;
        STATUS_val(1) <= STATUS_TX_EMPTY;
        STATUS_val(2) <= STATUS_RX_VALID;
    end process;
    
    -- Connections for DIV
    process(DIV_reg)
    begin
        DIV_val <= (others => '0');
        DIV_val(0) <= DIV_reg(0);
        DIV_DIVISOR <= DIV_reg(0);
    end process;
    
    -- Connections for TX_DATA
    process(TX_DATA_reg)
    begin
        TX_DATA_val <= (others => '0');
        TX_DATA_val(0) <= TX_DATA_reg(0);
        TX_DATA_DATA <= TX_DATA_reg(0);
    end process;
    
    -- Connections for RX_DATA
    process(RX_DATA_reg, RX_DATA_DATA)
    begin
        RX_DATA_val <= (others => '0');
        RX_DATA_val(0) <= RX_DATA_DATA;
    end process;
    
    
    ---------------------------------------------------------------------------
    -- AXI4-Lite Interface State Machine
    -- Full protocol compliance per ARM AMBA AXI4-Lite specification:
    --   - AXI-LITE-001: Safe reset state for all outputs
    --   - AXI-LITE-004: VALID stability until READY
    --   - AXI-LITE-005: Independent write address and data channels
    --   - AXI-LITE-007/008: Correct response timing
    --   - AXI-LITE-016/017: Delayed and early READY handling
    ---------------------------------------------------------------------------
    process(axi_aclk)
    begin
        if rising_edge(axi_aclk) then
            if axi_aresetn = '0' then
                -- AXI-LITE-001: Reset State Requirements
                axi_state <= IDLE;
                axi_awready <= '0';
                axi_wready <= '0';
                axi_bvalid <= '0';
                axi_bresp <= "00";
                axi_arready <= '0';
                axi_rvalid <= '0';
                axi_rresp <= "00";
                wr_access_error <= '0';
                rd_access_error <= '0';
                do_reg_write <= '0';
            else
                -- Default: clear one-shot signals
                do_reg_write <= '0';
                
                case axi_state is
                    ------------------------------------
                    -- IDLE: Wait for transaction start
                    ------------------------------------
                    when IDLE =>
                        -- Check for write transaction (address or data can come first)
                        -- AXI-LITE-005: Write Address and Data Independence
                        if axi_awvalid = '1' and axi_wvalid = '1' then
                            -- Both address and data arrived simultaneously
                            axi_awready <= '1';
                            axi_wready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_DO_WRITE;
                        elsif axi_awvalid = '1' then
                            -- Address first - wait for data
                            axi_awready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_WAIT_DATA;
                        elsif axi_wvalid = '1' then
                            -- Data first - wait for address
                            axi_wready <= '1';
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            axi_state <= WR_WAIT_ADDR;
                        elsif axi_arvalid = '1' then
                            -- Read transaction
                            axi_arready <= '1';
                            rd_addr_reg <= axi_araddr;
                            rd_access_error <= rd_addr_valid_n;
                            axi_state <= RD_ADDR;
                        end if;
                    
                    ------------------------------------
                    -- WR_WAIT_ADDR: Data received, waiting for address
                    -- AXI-LITE-005: Data-first ordering support
                    ------------------------------------
                    when WR_WAIT_ADDR =>
                        axi_wready <= '0';
                        if axi_awvalid = '1' then
                            axi_awready <= '1';
                            wr_addr_reg <= axi_awaddr;
                            wr_access_error <= wr_addr_valid_n;
                            axi_state <= WR_DO_WRITE;
                        end if;
                    
                    ------------------------------------
                    -- WR_WAIT_DATA: Address received, waiting for data
                    -- AXI-LITE-005: Address-first ordering support
                    ------------------------------------
                    when WR_WAIT_DATA =>
                        axi_awready <= '0';
                        if axi_wvalid = '1' then
                            axi_wready <= '1';
                            wr_data_reg <= axi_wdata;
                            wr_strb_reg <= axi_wstrb;
                            axi_state <= WR_DO_WRITE;
                        end if;
                    
                    ------------------------------------
                    -- WR_DO_WRITE: Perform register write
                    ------------------------------------
                    when WR_DO_WRITE =>
                        axi_awready <= '0';
                        axi_wready <= '0';
                        do_reg_write <= '1';  -- Trigger register write
                        axi_state <= WR_RESP;
                        axi_bvalid <= '1';
                        -- AXI-LITE-014: Response Code Compliance
                        if wr_access_error = '1' then
                            axi_bresp <= "10"; -- SLVERR
                        else
                            axi_bresp <= "00"; -- OKAY
                        end if;
                    
                    ------------------------------------
                    -- WR_RESP: Wait for response acknowledgment
                    -- AXI-LITE-007: Write Response Timing
                    ------------------------------------
                    when WR_RESP =>
                        -- AXI-LITE-016/017: READY handling (immediate or delayed)
                        if axi_bready = '1' then
                            axi_bvalid <= '0';
                            axi_bresp <= "00";
                            axi_state <= IDLE;
                        end if;
                    
                    ------------------------------------
                    -- RD_ADDR: Read address received
                    ------------------------------------
                    when RD_ADDR =>
                        axi_arready <= '0';
                        axi_state <= RD_DATA;
                        axi_rvalid <= '1';
                        -- AXI-LITE-014: Response Code Compliance
                        if rd_access_error = '1' then
                            axi_rresp <= "10"; -- SLVERR
                        else
                            axi_rresp <= "00"; -- OKAY
                        end if;
                    
                    ------------------------------------
                    -- RD_DATA: Output read data
                    -- AXI-LITE-008: Read Response Timing
                    -- AXI-LITE-016/017: READY handling
                    ------------------------------------
                    when RD_DATA =>
                        if axi_rready = '1' then
                            axi_rvalid <= '0';
                            axi_rresp <= "00";
                            axi_state <= IDLE;
                        end if;
                end case;
            end if;
        end if;
    end process;
    
    -- Write Address Valid Detection (combinational)
    process(axi_awaddr)
    begin
        wr_addr_valid_n <= '1';  -- Default: invalid
        if unsigned(axi_awaddr) = unsigned(BASE_ADDR) + 0 then
            wr_addr_valid_n <= '0';  -- Valid write address (CTRL packed)
        end if;
        if unsigned(axi_awaddr) = unsigned(BASE_ADDR) + 8 then
            wr_addr_valid_n <= '0';  -- Valid write address (DIV packed)
        end if;
        if unsigned(axi_awaddr) = unsigned(BASE_ADDR) + 12 then
            wr_addr_valid_n <= '0';  -- Valid write address (TX_DATA packed)
        end if;
    end process;
    
    -- Read Address Valid Detection (combinational)
    process(axi_araddr)
    begin
        rd_addr_valid_n <= '1';  -- Default: invalid
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 0 then
            rd_addr_valid_n <= '0';  -- Valid read address (CTRL packed)
        end if;
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 4 then
            rd_addr_valid_n <= '0';  -- Valid read address (STATUS packed)
        end if;
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 8 then
            rd_addr_valid_n <= '0';  -- Valid read address (DIV packed)
        end if;
        if unsigned(axi_araddr) = unsigned(BASE_ADDR) + 16 then
            rd_addr_valid_n <= '0';  -- Valid read address (RX_DATA packed)
        end if;
    end process;
    
    -- Register Write Logic
    -- Write occurs when do_reg_write is asserted (WR_DO_WRITE state)
    process(axi_aclk)
    begin
        if rising_edge(axi_aclk) then
            if axi_aresetn = '0' then
                CTRL_reg <= (others => '0');
                DIV_reg <= (others => '0');
                TX_DATA_reg <= (others => '0');
            else
                if do_reg_write = '1' and wr_access_error = '0' then
                    if unsigned(wr_addr_reg) = unsigned(BASE_ADDR) + 0 then
                        -- Byte-level write strobe
                        if wr_strb_reg(0) = '1' then
                            CTRL_reg(7 downto 0) <= wr_data_reg(7 downto 0);
                        end if;
                        if wr_strb_reg(1) = '1' then
                            CTRL_reg(15 downto 8) <= wr_data_reg(15 downto 8);
                        end if;
                        if wr_strb_reg(2) = '1' then
                            CTRL_reg(23 downto 16) <= wr_data_reg(23 downto 16);
                        end if;
                        if wr_strb_reg(3) = '1' then
                            CTRL_reg(31 downto 24) <= wr_data_reg(31 downto 24);
                        end if;
                    end if;
                    if unsigned(wr_addr_reg) = unsigned(BASE_ADDR) + 8 then
                        -- Byte-level write strobe
                        if wr_strb_reg(0) = '1' then
                            DIV_reg(7 downto 0) <= wr_data_reg(7 downto 0);
                        end if;
                        if wr_strb_reg(1) = '1' then
                            DIV_reg(15 downto 8) <= wr_data_reg(15 downto 8);
                        end if;
                        if wr_strb_reg(2) = '1' then
                            DIV_reg(23 downto 16) <= wr_data_reg(23 downto 16);
                        end if;
                        if wr_strb_reg(3) = '1' then
                            DIV_reg(31 downto 24) <= wr_data_reg(31 downto 24);
                        end if;
                    end if;
                    if unsigned(wr_addr_reg) = unsigned(BASE_ADDR) + 12 then
                        -- Byte-level write strobe
                        if wr_strb_reg(0) = '1' then
                            TX_DATA_reg(7 downto 0) <= wr_data_reg(7 downto 0);
                        end if;
                        if wr_strb_reg(1) = '1' then
                            TX_DATA_reg(15 downto 8) <= wr_data_reg(15 downto 8);
                        end if;
                        if wr_strb_reg(2) = '1' then
                            TX_DATA_reg(23 downto 16) <= wr_data_reg(23 downto 16);
                        end if;
                        if wr_strb_reg(3) = '1' then
                            TX_DATA_reg(31 downto 24) <= wr_data_reg(31 downto 24);
                        end if;
                    end if;
                end if;
            end if;
        end if;
    end process;
    
    -- Register Read Logic
    process(rd_addr_reg, rd_access_error
        , CTRL_val
        , STATUS_val
        , DIV_val
        , RX_DATA_val
    )
    begin
        rd_data_reg <= (others => '0');
        if rd_access_error = '0' then
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 0 then
                rd_data_reg <= CTRL_val;
            end if;
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 4 then
                rd_data_reg <= STATUS_val;
            end if;
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 8 then
                rd_data_reg <= DIV_val;
            end if;
            if unsigned(rd_addr_reg) = unsigned(BASE_ADDR) + 16 then
                rd_data_reg <= RX_DATA_val;
            end if;
        end if;
    end process;
    
    axi_rdata <= rd_data_reg;
    
    
    
    
    
    
end architecture rtl;
