/**
 * @file spi_master_0_regs.h
 * @brief Register definitions for spi_master_0 module
 * @note Generated by Axion HDL - Do not edit manually
 *
 * All register definitions use module prefix to avoid namespace collisions
 * when multiple modules are included in the same project.
 */

#ifndef SPI_MASTER_0_REGS_H
#define SPI_MASTER_0_REGS_H

#include <stdint.h>

/* Module Base Address */
#define SPI_MASTER_0_BASE_ADDR    0x40000000

/* Register Address Offsets (relative to base) */
#define SPI_MASTER_0_CTRL_OFFSET    0x00  /* Packed register: CTRL */
#define SPI_MASTER_0_STATUS_OFFSET    0x04  /* Packed register: STATUS */
#define SPI_MASTER_0_DIV_OFFSET    0x08  /* Packed register: DIV */
#define SPI_MASTER_0_TX_DATA_OFFSET    0x0C  /* Packed register: TX_DATA */
#define SPI_MASTER_0_RX_DATA_OFFSET    0x10  /* Packed register: RX_DATA */

/* Absolute Register Addresses */
#define SPI_MASTER_0_CTRL_ADDR    0x00
#define SPI_MASTER_0_STATUS_ADDR    0x04
#define SPI_MASTER_0_DIV_ADDR    0x08
#define SPI_MASTER_0_TX_DATA_ADDR    0x0C
#define SPI_MASTER_0_RX_DATA_ADDR    0x10

/* Signal Width Definitions (for multi-register signals) */
/* No signals wider than 32 bits */

/* Register Access Macros (using module base address) */
/* Helper macros for bit field access */
#ifndef GET_FIELD
#define GET_FIELD(val, mask, shift)    (((val) & (mask)) >> (shift))
#endif

#ifndef SET_FIELD
#define SET_FIELD(val, mask, shift, new_val)    (((val) & ~(mask)) | (((new_val) << (shift)) & (mask)))
#endif
#define SPI_MASTER_0_READ_CTRL()    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_CTRL_OFFSET)))
#define SPI_MASTER_0_READ_STATUS()    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_STATUS_OFFSET)))
#define SPI_MASTER_0_READ_DIV()    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_DIV_OFFSET)))
#define SPI_MASTER_0_READ_RX_DATA()    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_RX_DATA_OFFSET)))

#define SPI_MASTER_0_WRITE_CTRL(val)    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_CTRL_OFFSET)) = (val))
#define SPI_MASTER_0_WRITE_DIV(val)    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_DIV_OFFSET)) = (val))
#define SPI_MASTER_0_WRITE_TX_DATA(val)    (*((volatile uint32_t*)(SPI_MASTER_0_BASE_ADDR + SPI_MASTER_0_TX_DATA_OFFSET)) = (val))

/* Bit Field Masks and Shifts (for packed registers) */
#define SPI_MASTER_0_CTRL_ENABLE_MASK    0x1
#define SPI_MASTER_0_CTRL_ENABLE_SHIFT   0
#define SPI_MASTER_0_CTRL_CPOL_MASK    0x2
#define SPI_MASTER_0_CTRL_CPOL_SHIFT   1
#define SPI_MASTER_0_CTRL_CPHA_MASK    0x4
#define SPI_MASTER_0_CTRL_CPHA_SHIFT   2
#define SPI_MASTER_0_CTRL_LOOPBACK_MASK    0x8
#define SPI_MASTER_0_CTRL_LOOPBACK_SHIFT   3
#define SPI_MASTER_0_STATUS_BUSY_MASK    0x1
#define SPI_MASTER_0_STATUS_BUSY_SHIFT   0
#define SPI_MASTER_0_STATUS_TX_EMPTY_MASK    0x2
#define SPI_MASTER_0_STATUS_TX_EMPTY_SHIFT   1
#define SPI_MASTER_0_STATUS_RX_VALID_MASK    0x4
#define SPI_MASTER_0_STATUS_RX_VALID_SHIFT   2
#define SPI_MASTER_0_DIV_DIVISOR_MASK    0x1
#define SPI_MASTER_0_DIV_DIVISOR_SHIFT   0
#define SPI_MASTER_0_TX_DATA_DATA_MASK    0x1
#define SPI_MASTER_0_TX_DATA_DATA_SHIFT   0
#define SPI_MASTER_0_RX_DATA_DATA_MASK    0x1
#define SPI_MASTER_0_RX_DATA_DATA_SHIFT   0

/* Register Default Values */
#define SPI_MASTER_0_CTRL_DEFAULT    0x00000000
#define SPI_MASTER_0_STATUS_DEFAULT    0x00000000
#define SPI_MASTER_0_DIV_DEFAULT    0x00000000
#define SPI_MASTER_0_TX_DATA_DEFAULT    0x00000000
#define SPI_MASTER_0_RX_DATA_DEFAULT    0x00000000

/* Register Structure */
typedef struct {
    volatile uint32_t CTRL;  /* 0x00 - RW - Packed register: CTRL */
    volatile uint32_t STATUS;  /* 0x04 - RO - Packed register: STATUS */
    volatile uint32_t DIV;  /* 0x08 - RW - Packed register: DIV */
    volatile uint32_t TX_DATA;  /* 0x0C - WO - Packed register: TX_DATA */
    volatile uint32_t RX_DATA;  /* 0x10 - RO - Packed register: RX_DATA */
} spi_master_regs_t;

/* Access register block as structure */
#define SPI_MASTER_0_REGS    ((volatile spi_master_regs_t*)(SPI_MASTER_0_BASE_ADDR))

#endif /* SPI_MASTER_0_REGS_H */
