//-----------------------------------------------------------------------------
// File: spi_master_0_axion_reg.sv
// Module: spi_master_0_axion_reg
// Description: AXI4-Lite Register Interface for spi_master_0
// Generated by: Axion-HDL
// Date: 2026-04-23 23:17:59
//
// This file was automatically generated. Manual modifications may be lost.
//-----------------------------------------------------------------------------

module spi_master_0_axion_reg #(
    parameter int ADDR_WIDTH = 32,
    parameter int DATA_WIDTH = 32
) (
    // AXI4-Lite Interface
    input  logic                      axi_aclk,
    input  logic                      axi_aresetn,
    input  logic [ADDR_WIDTH-1:0]     axi_awaddr,
    input  logic [2:0]                axi_awprot,
    input  logic                      axi_awvalid,
    output logic                      axi_awready,
    input  logic [DATA_WIDTH-1:0]     axi_wdata,
    input  logic [(DATA_WIDTH/8)-1:0] axi_wstrb,
    input  logic                      axi_wvalid,
    output logic                      axi_wready,
    output logic [1:0]                axi_bresp,
    output logic                      axi_bvalid,
    input  logic                      axi_bready,
    input  logic [ADDR_WIDTH-1:0]     axi_araddr,
    input  logic [2:0]                axi_arprot,
    input  logic                      axi_arvalid,
    output logic                      axi_arready,
    output logic [DATA_WIDTH-1:0]     axi_rdata,
    output logic [1:0]                axi_rresp,
    output logic                      axi_rvalid,
    input  logic                      axi_rready,

    // Register Interface
    output logic [31:0]                   CTRL,
    input  logic [31:0]                   STATUS,
    output logic [31:0]                   DIV,
    output logic [31:0]                   TX_DATA,
    input  logic [31:0]                   RX_DATA
);

    // AXI4-Lite response codes
    localparam [1:0] OKAY   = 2'b00;
    localparam [1:0] SLVERR = 2'b10;

    // Register addresses
    localparam [ADDR_WIDTH-1:0] ADDR_CTRL = 32'h00000000;
    localparam [ADDR_WIDTH-1:0] ADDR_STATUS = 32'h00000004;
    localparam [ADDR_WIDTH-1:0] ADDR_DIV = 32'h00000008;
    localparam [ADDR_WIDTH-1:0] ADDR_TX_DATA = 32'h0000000C;
    localparam [ADDR_WIDTH-1:0] ADDR_RX_DATA = 32'h00000010;

    //-------------------------------------------------------------------------
    // Struct Definitions
    //-------------------------------------------------------------------------

    typedef struct packed {
        logic        ENABLE;
        logic        CPOL;
        logic        CPHA;
        logic        LOOPBACK;
    } CTRL_t;

    typedef struct packed {
        logic        BUSY;
        logic        TX_EMPTY;
        logic        RX_VALID;
    } STATUS_t;

    typedef struct packed {
        logic        DIVISOR;
    } DIV_t;

    typedef struct packed {
        logic        DATA;
    } TX_DATA_t;

    typedef struct packed {
        logic        DATA;
    } RX_DATA_t;


    // AXI4-Lite state machine
    typedef enum logic [2:0] {
        IDLE,
        WRITE_ADDR,
        WRITE_DATA,
        WRITE_RESP,
        READ_ADDR,
        READ_DATA
    } axi_state_t;

    axi_state_t state, next_state;

    // Internal registers
    CTRL_t                     CTRL_reg;
    DIV_t                     DIV_reg;
    TX_DATA_t                     TX_DATA_reg;

    // Internal signals
    logic [DATA_WIDTH-1:0] rdata_reg;
    logic [1:0]            rresp_reg;
    logic [1:0]            bresp_reg;
    logic [ADDR_WIDTH-1:0] write_addr;
    logic [ADDR_WIDTH-1:0] read_addr;

    // Sink for unused signals to silence lint warnings
    logic _unused_ok;
    assign _unused_ok = &{1'b0, axi_awprot, axi_arprot, axi_wstrb, axi_wdata, 1'b0};


    //-------------------------------------------------------------------------
    // AXI4-Lite State Machine
    //-------------------------------------------------------------------------

    // State register
    always_ff @(posedge axi_aclk or negedge axi_aresetn) begin
        if (!axi_aresetn) begin
            state <= IDLE;
        end else begin
            state <= next_state;
        end
    end

    // Next state logic
    always_comb begin
        next_state = state;

        case (state)
            IDLE: begin
                if (axi_awvalid) begin
                    next_state = WRITE_ADDR;
                end else if (axi_arvalid) begin
                    next_state = READ_ADDR;
                end
            end

            WRITE_ADDR: begin
                if (axi_wvalid) begin
                    next_state = WRITE_DATA;
                end
            end

            WRITE_DATA: begin
                next_state = WRITE_RESP;
            end

            WRITE_RESP: begin
                if (axi_bready) begin
                    next_state = IDLE;
                end
            end

            READ_ADDR: begin
                next_state = READ_DATA;
            end

            READ_DATA: begin
                if (axi_rready) begin
                    next_state = IDLE;
                end
            end

            default: begin
                next_state = IDLE;
            end
        endcase
    end

    // Output logic
    assign axi_awready = (state == WRITE_ADDR);
    assign axi_wready  = (state == WRITE_DATA);
    assign axi_bvalid  = (state == WRITE_RESP);
    assign axi_bresp   = bresp_reg;
    assign axi_arready = (state == READ_ADDR);
    assign axi_rvalid  = (state == READ_DATA);
    assign axi_rdata   = rdata_reg;
    assign axi_rresp   = rresp_reg;


    //-------------------------------------------------------------------------
    // Register Logic
    //-------------------------------------------------------------------------

    // Address capture
    always_ff @(posedge axi_aclk or negedge axi_aresetn) begin
        if (!axi_aresetn) begin
            write_addr <= '0;
            read_addr <= '0;
        end else begin
            if (state == WRITE_ADDR && axi_awvalid) begin
                write_addr <= axi_awaddr;
            end
            if (state == READ_ADDR && axi_arvalid) begin
                read_addr <= axi_araddr;
            end
        end
    end

    // Register write logic
    always_ff @(posedge axi_aclk or negedge axi_aresetn) begin
        if (!axi_aresetn) begin
            CTRL_reg <= 32'd0;
            DIV_reg <= 32'd0;
            TX_DATA_reg <= 32'd0;
            bresp_reg <= OKAY;
        end else begin

            if (state == WRITE_DATA && axi_wvalid) begin
                case (write_addr)
                    ADDR_CTRL: begin
                        CTRL_reg <= axi_wdata;
                        bresp_reg <= OKAY;
                    end
                    ADDR_STATUS: begin
                        bresp_reg <= SLVERR;
                    end
                    ADDR_DIV: begin
                        DIV_reg <= axi_wdata;
                        bresp_reg <= OKAY;
                    end
                    ADDR_TX_DATA: begin
                        TX_DATA_reg <= axi_wdata;
                        bresp_reg <= OKAY;
                    end
                    ADDR_RX_DATA: begin
                        bresp_reg <= SLVERR;
                    end
                    default: begin
                        bresp_reg <= SLVERR;
                    end
                endcase
            end
        end
    end

    // Register read logic
    always_comb begin
        rdata_reg = '0;
        rresp_reg = OKAY;

        case (read_addr)
            ADDR_CTRL: begin
                rdata_reg = CTRL_reg;
            end
            ADDR_STATUS: begin
                rdata_reg = STATUS;
            end
            ADDR_DIV: begin
                rdata_reg = DIV_reg;
            end
            ADDR_TX_DATA: begin
                rresp_reg = SLVERR;
            end
            ADDR_RX_DATA: begin
                rdata_reg = RX_DATA;
            end
            default: begin
                rresp_reg = SLVERR;
            end
        endcase
    end


    //-------------------------------------------------------------------------
    // Output Assignments
    //-------------------------------------------------------------------------

    assign CTRL = CTRL_reg;
    assign DIV = DIV_reg;
    assign TX_DATA = TX_DATA_reg;

endmodule
